String.toLocaleString({
	"en": {
		"%gmapNotSupported": "If this doesn't load, maybe your browser doesn't support GMaps",
		"%eastPanel": "Options Menu",
		"%userForm": "User Information",
		"%categories": "Categories",
		"%category": "Category",
		"%logged": "You are logged in as ",
		"%login": "Log in",
		"%user": "User",
		"%password": "Password",
		"%errMissing": "All fields must be filled&#46;",
		"%errConnection": "There was a connection problem. Please, try again later.",
		"%errInvalidLogin": "Wrong login/password",
		"%err": "Erro!",
		"%strZoomIn": "Zoom In",
		"%strZoomOut": "Zoom Out",
		"%zoomInHere": "Zoom In Here",
		"%zoomOutHere": "Zoom Out Here",
		"%register": "Register in the forum or do login first!",
		"%addMarker": "Add Marker",
		"%edit": "Edit",
		"%delete": "Delete",
		"%title": "Title",
		"%information": "Information",
		"%tabTitle": "Tab Title",
		"%tabDescription": "Description",
		"%addMarkerHelper": "To add information, click on the &quot;plus&quot; button and fill out the tab title and description.",
		"%success": "Success!",
		"%addMarkerSuccessText": "Mark sent sucessfully! You will be notified as soon as it is approved",
		"%submit": "Submit",
		"%cancel": "Cancel",
		"%tab": "Tab",
		"%sentBy": "Sent by: ",
		"%deletMarkerTitle": "Removal of marker",
		"%deletMarkerText": "You're deleting the marker, not the tab! To delete the tab, enter edit mode.",
		"%deletMarkerText2": "Please, describe a reason to delete:",
		"%moveMarkerTitle": "Move of marker",
		"%moveMarkerText": "Please, describe a reason to move the marker:",
		"%jumpMarkerTitleInfo": "Add a jump marker!",
		"%jumpMarkerTextInfo1": "Please add a title for the origin marker!",		
		"%jumpMarkerTextInfo2": "Click anywhere on the map or at another marker to create a link between the origin marker and the clicked position.",
		"%jumpMarkerTextInfo3": "Please add a title for the destination marker!",
		"%jumpMarkerTitleConfirm": "Jump marker creation confirmation!",
		"%jumpMarkerTextConfirm": "Please describe a reason for this link!",
		"%userMarkerSettingsTitle": "User Options",
		"%userMarkerSettingsMyMarkers": "Show only my markers",
		"%userMarkerSettingsApproved": "All approved markers",
		"%userMarkerSettingsNotApproved": "All non-approved markers",
		"%globalMarker": "Global Marker?",
		"%tutoTitle1": "Tutorial - page %c of %t",
		"%tuto1": "Welcome to the open beta of Zelda Maps!<br><br>Zelda Maps is one of the best way to view game maps and share your knowledge.<br><br>This tutorial will guide you through all the features we have so you can make the best of it! Since we use the Googlemaps API, you should be familiar with a lots of elements present there.<br><br>So, Let's get started!",
		"%tutoTitle2": "The Map Interface - page %c of %t",
		"%tuto2": "User interface overview:<BR><BR><img src='tutorial/tuto1.png' width='300' height='170'><br><br>1- Multiple selectable maps<BR>2- Selectable Floors/Instances (only 1 per time)<BR>3- Selectable Layers (multiple per time)<br>4- Interactive Markers (click on them!)<BR>5-. User information/configuration<BR>6- Category Filter<BR>7- Mapper information",
		"%tutoTitle3": "Interactive Markers - page %c of %t",
		"%tuto3": "Interactive Markers are the heart and soul of this system.<br>You can click on them on any given type to get insightful<br>information regarding that marker.<br><br>To add a marker, you needed to be logged in our forums.<br>Just right click anywhere on the map to bring a drop down<br>menu that with all the available options.<br><br>You can also right click on a marker you<br>previously inserted to bring up another menu.<br><br><img src='tutorial/tuto2.png' width='367' height='215'><br>",
		"%tutoTitle4": "Types of Markers - page %c of %t",
		"%tuto4": "<center>Markers come in three different shapes:<br><br><table align=center cellspacing='20'><tr><td align=center>Information marker</td><td align=center>Jump Marker</td></tr><td><img src='tutorial/tuto3a.png' width=200 height=158>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;<img src='tutorial/tuto3b.png' width=200 height=158></td></tr></table><br>Label Marker<br><img src='tutorial/tuto3c.png' width=200 height=158></center>",
		"%tutoTitle5": "Floors/Instances - page %c of %t",
		"%tuto5": "Some maps have options to view different sections of the map, such as dungeons, present/future, light/dark world.<br><br><center><img src='tutorial/tuto4.png' width='256' height='256'></center><br><br>By clicking on the corresponding section, you can easily switch between those sections.<br><br>Please do note that markers are shown according not only to the map, but also the section (unless marked as global on insertion)",
		"%tutoTitle6": "Layers - page %c of %t",
		"%tuto6": "Some maps also have the layers feature, which you can enable or disable by clicking on them, adding more depth to a given by map.<br><br><center><img src='tutorial/tuto5.png' width='256' height='256'></center><br><br>For example, a dungeon map could have 4 layers, such as the background, the floor, the enemies/allies, the secrets. You can easily switch between on/off of them by clicking on the corresponding element.<br><br>Layers <b>do not</b> affect markers placement onto the map.",
		"%tutoTitle7": "End of tutorial - page %c of %t",
		"%tuto7": "That's it for now!<br><br>We have put a lot of effort on this and we hope that you like it. We sincerly hope that you share you knowledge and enjoy the maps!<br><br>Any questions, issues, critics, go to our forum: zelda.com.br/forum.<br><br><center><img src='tutorial/tuto6.png' width='224' height='80'><br><b>It's dangerous to go alone. Here, use our maps!</b></center>",
		"%tutorialDontShow": "Don't show this again!",
		"%tutorialPrevious": "Previous",
		"%tutorialNext": "Next"
	},
	"pt": {
		"%gmapNotSupported": "Caso o mapa n&#227;o carregue, seu navegador n&#227;o suporta o Google Maps.",
		"%eastPanel": "Menu de op&#231;&#245;es",
		"%userForm": "Informa&#231;&#245;es do usu&#225;rio",
		"%categories": "Categorias",
		"%category": "Categoria",
		"%logged": "Voc&#234; est&#225; logado como ",
		"%login": "Entrar",
		"%user": "Usu&#225;rio",
		"%password": "Senha",
		"%errMissing": "Todos os campos devem ser preenchidos&#46;",
		"%errConnection": "Houve um erro de conex&#227;o com o servidor&#46; Por favor, tente novamente.",
		"%errInvalidLogin": "Login/Senhas inv&#225;lidos",
		"%err": "Erro!",
		"%strZoomIn": "Aumentar zoom",
		"%strZoomOut": "Diminuir zoom",
		"%zoomInHere": "Aumentar zoom aqui",
		"%zoomOutHere": "Diminuir zoom aqui",
		"%register": "Registre-se no f&#243;rum / fa&#231;a login primeiro!",
		"%addMarker": "Adcionar marcador",
		"%edit": "Editar",
		"%delete": "Deletar",
		"%title": "T&#237;tulo",
		"%information": "Informa&#231;&#227;o",
		"%tabTitle": "T&#237;tulo",
		"%tabDescription": "Descri&#231;&#227;o",
		"%addMarkerHelper": "Para adicionar conte&#250;do, clique no bot&#227;o &quot;mais&quot; acima e preencha os campos de t&#237;tulo e descri&#231;&#227;o da aba.",
		"%success": "Sucesso!",
		"%addMarkerSuccessText": "Assim que o marcador for aprovado&#44; voc&#234; ser&#225; notificado&#46;",
		"%submit": "Enviar",
		"%cancel": "Cancelar",
		"%tab": "Aba",
		"%sentBy": "Enviado por: ",
		"%deletMarkerTitle": "Confirma&#231;&#227;o de dele&#231;&#227;o",
		"%deletMarkerText": "A dele&#231;&#227;o &#233; do marcador, n&#227;o da aba! Para deletar uma aba, entre em modo de edi&#231;&#227;o.",
		"%deletMarkerText2": "Descreva o motivo para dele&#231;&#227;o:",
		"%moveMarkerTitle": "Confirma&#231;&#227;o de movimenta&#231;&#227;o",
		"%moveMarkerText": "Descreva o motivo da nova posi&#231;&#227;o:",
		"%jumpMarkerTitleInfo": "Cria&#231;&#227;o de marcador de pulo!",
		"%jumpMarkerTextInfo1": "Por favor, informe um t&#237;tulo para o marcador de origem!",		
		"%jumpMarkerTextInfo2": "Clique em qualquer lugar do mapa ou em outro marcador para criar um v&#237;nculo com o marcador de origem.",
		"%jumpMarkerTextInfo3": "Por favor, informe um t&#237;tulo para o marcador de destino!",
		"%jumpMarkerTitleConfirm": "Confirma&#231;&#227;o de cria&#231;&#227;o de marcador de pulo!",
		"%jumpMarkerTextConfirm": "Por favor, descreva a raz&#227;o para a cria&#231;&#227;o desse v&#237;nculo!",
		"%userMarkerSettingsTitle": "Op&#231;&#245;es do usu&#225;rio",
		"%userMarkerSettingsMyMarkers": "Mostrar apenas meus marcadores",
		"%userMarkerSettingsApproved": "Todos os aprovados",
		"%userMarkerSettingsNotApproved": "Todos os n&#227;o aprovados",
		"%globalMarker": "Marcador global?",
		"%tutoTitle1": "Tutorial - page %c of %t",
		"%tuto1": "Welcome to the open beta of Zelda Maps!<br><br>Zelda Maps is one of the best way to view game maps and share your knowledge.<br><br>This tutorial will guide you through all the features we have so you can make the best of it! Since we use the Googlemaps API, you should be familiar with a lots of elements present there.<br><br>So, Let's get started!",
		"%tutoTitle2": "The Map Interface - page %c of %t",
		"%tuto2": "User interface overview:<BR><BR><img src='tutorial/tuto1.png' width='300' height='170'><br><br>1- Multiple selectable maps<BR>2- Selectable Floors/Instances (only 1 per time)<BR>3- Selectable Layers (multiple per time)<br>4- Interactive Markers (click on them!)<BR>5-. User information/configuration<BR>6- Category Filter<BR>7- Mapper information",
		"%tutoTitle3": "Interactive Markers - page %c of %t",
		"%tuto3": "Interactive Markers are the heart and soul of this system.<br>You can click on them on any given type to get insightful<br>information regarding that marker.<br><br>To add a marker, you needed to be logged in our forums.<br>Just right click anywhere on the map to bring a drop down<br>menu that with all the available options.<br><br>You can also right click on a marker you<br>previously inserted to bring up another menu.<br><br><img src='tutorial/tuto2.png' width='367' height='215'><br>",
		"%tutoTitle4": "Types of Markers - page %c of %t",
		"%tuto4": "<center>Markers come in three different shapes:<br><br><table align=center cellspacing='20'><tr><td align=center>Information marker</td><td align=center>Jump Marker</td></tr><td><img src='tutorial/tuto3a.png' width=200 height=158>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;<img src='tutorial/tuto3b.png' width=200 height=158></td></tr></table><br>Label Marker<br><img src='tutorial/tuto3c.png' width=200 height=158></center>",
		"%tutoTitle5": "Floors/Instances - page %c of %t",
		"%tuto5": "Some maps have options to view different sections of the map, such as dungeons, present/future, light/dark world.<br><br><center><img src='tutorial/tuto4.png' width='256' height='256'></center><br><br>By clicking on the corresponding section, you can easily switch between those sections.<br><br>Please do note that markers are shown according not only to the map, but also the section (unless marked as global on insertion)",
		"%tutoTitle6": "Layers - page %c of %t",
		"%tuto6": "Some maps also have the layers feature, which you can enable or disable by clicking on them, adding more depth to a given by map.<br><br><center><img src='tutorial/tuto5.png' width='256' height='256'></center><br><br>For example, a dungeon map could have 4 layers, such as the background, the floor, the enemies/allies, the secrets. You can easily switch between on/off of them by clicking on the corresponding element.<br><br>Layers <b>do not</b> affect markers placement onto the map.",
		"%tutoTitle7": "End of tutorial - page %c of %t",
		"%tuto7": "That's it for now!<br><br>We have put a lot of effort on this and we hope that you like it. We sincerly hope that you share you knowledge and enjoy the maps!<br><br>Any questions, issues, critics, go to our forum: zelda.com.br/forum.<br><br><center><img src='tutorial/tuto6.png' width='224' height='80'><br><b>It's dangerous to go alone. Here, use our maps!</b></center>",
		"%tutorialDontShow": "Don't show this again!",
		"%tutorialPrevious": "Previous",
		"%tutorialNext": "Next"
	}
});
